#!/usr/bin/env perl

use strict;
use warnings;

use lib 'lib';

# packages needed for this app
# SQL::TRANSLATOR
# DBIX::CORE
# SQLITE3
# DBIx::Class::Migration
# Mojolicious::Plugin::Bcrypt
# Start command line interface for application
#DBIx::Class::InflateColumn::Boolean
# DBIx::Class::InflateColumn::Currency

#when database upgrade change our $version in /lib/moblo/Schema.pm
#dbic-migration -S 'Moblo::Schema' -Ilib --database SQLite prepare
#dbic-migration -S 'Moblo::Schema' -Ilib --database SQLite install
#or
#dbic-migration -S 'Moblo::Schema' -Ilib --database SQLite upgrade

#has_many realationship (that is zero or more records in the foriegn tabel post)
#has_one relationship Posts -> User(one autor per post)
#belongs_to relationship Comments -> Posts Comments -> Users each comment has a foreign key to one user and post
#relation ships are added for each table to the bottom of each associated result class
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Moblo');
