#!/usr/bin/env perl

use strict;
use warnings;

use lib 'lib';

# packages needed for this app
# SQL::TRANSLATOR
# DBIX::CORE
# SQLITE3
# DBIx::Class::Migration
# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Moblo');
